s

diff --git a/.github/workflows/gradle-master-pull.yml b/.github/workflows/gradle-master-pull.yml
--- a/.github/workflows/gradle-master-pull.yml
+++ b/.github/workflows/gradle-master-pull.yml
@@ -46,11 +46,11 @@ jobs:
 #        working-directory: ./backend
 #        run: ./gradlew test
 
-      - name: Successful tests
-        if: steps.test.outcome != 'success'
-        run: |
-          echo "Tests error"
-          exit 1
+#      - name: Successful tests
+#        if: steps.test.outcome != 'success'
+#        run: |
+#          echo "Tests error"
+#          exit 1
           
       - name: Use Node.js 18
         uses: actions/setup-node@v3
diff --git a/.github/workflows/gradle-master-push.yml b/.github/workflows/gradle-master-push.yml
--- a/.github/workflows/gradle-master-push.yml
+++ b/.github/workflows/gradle-master-push.yml
@@ -41,11 +41,11 @@ jobs:
 #        working-directory: ./backend
 #        run: ./gradlew test
 
-      - name: Successful tests
-        if: steps.test.outcome != 'success'
-        run: |
-          echo "Tests error"
-          exit 1
+#      - name: Successful tests
+#        if: steps.test.outcome != 'success'
+#        run: |
+#          echo "Tests error"
+#          exit 1
 
       - name: Successful build
         uses: appleboy/telegram-action@master
