split activity

diff --git a/.github/workflows/gradle-master-push.yml b/.github/workflows/gradle-master-push.yml
--- a/.github/workflows/gradle-master-push.yml
+++ b/.github/workflows/gradle-master-push.yml
@@ -1,9 +1,7 @@
-name: Master CI
+name: Master push CI/CD
 
 on:
   push:
-    branches: [ "master" ]
-  pull_request:
     branches: [ "master" ]
 
 jobs:
@@ -49,8 +47,8 @@ jobs:
           to: ${{ secrets.TELEGRAM_ME }}
           token: ${{ secrets.TELEGRAM_NOT }}
           message: |
-            ✅ Application build done
-            Check report on https://github.com/IvanDuvanOFF/MigApp/actions
+            ✅ Application tests done
+            Check report on https://github.com/${{ github.repository }}/actions
 
       - name: Send alert in Telegram
         if: failure()
@@ -59,8 +57,8 @@ jobs:
           to: ${{ secrets.TELEGRAM_ME }}
           token: ${{ secrets.TELEGRAM_NOT }}
           message: |
-            ❌ Failed to build
-            Check report on https://github.com/IvanDuvanOFF/MigApp/actions
+            ❌ Tests failed
+            Check report on https://github.com/${{ github.repository }}/actions
 
   send-project:
     name: Sends project to server
@@ -136,6 +134,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: executing remote ssh commands using password
+        id: deploy
         uses: appleboy/ssh-action@v1.0.3
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -156,3 +155,29 @@ jobs:
             cd /app/mig-api/backend
 
             docker compose up -d > logs.txt
+
+      - name: Successful tests
+        if: steps.deploy.outcome != 'success'
+        run: |
+          echo "Tests error"
+          exit 1
+
+      - name: Successful deploy
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_ME }}
+          token: ${{ secrets.TELEGRAM_NOT }}
+          message: |
+            ✅ Application deploy done
+            Check it on link:
+            http://${{ SERVER_HOST }}/actuator/health
+
+      - name: Send alert in Telegram
+        if: failure()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_ME }}
+          token: ${{ secrets.TELEGRAM_NOT }}
+          message: |
+            ❌ Application deploy failed
+            Check report on https://github.com/${{ github.repository }}/actions
